#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Build only for commits to certain locations
only_commits:
  files:
    - dtocean_moorings/
    - tests/
    - setup.py
    
skip_commits:
  files:
    - dtocean_moorings/config/

# version format
version: 2.0.0.build{build}

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      ARCH: "32"
      
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      ARCH: "64"


init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - conda create -n _dtocean-moor python=%PYTHON_VERSION% pip
  - activate _dtocean-moor
  - copy .condarc %CONDA_PREFIX%
  - conda install polite=0.10.0
  - conda install --file requirements-conda-dev.txt
  - pip install -e .
  - conda install pytest pytest-cov pytest-mock
  
build: off
  
test_script:
  - py.test --cov dtocean_moorings tests
  
after_test:
 - pip install codecov
 - codecov
  